# Generated by Django 3.1.2 on 2021-05-12 08:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 8, 44, 27, 404881, tzinfo=utc)),
        ),
    ]
